#!/bin/bash

SSHPASS="/usr/bin/sshpass"
SSH="/usr/bin/ssh"
AWK="/usr/bin/awk"
SUDO="/usr/bin/sudo"
GREP="/usr/bin/grep"

IP="$1"
USER="zabbix"
COMMAND="lssystemstats"
VAR1="$2"

stat_peak=$($SSH $USER@$IP "$COMMAND" | $GREP "$VAR1" | $AWK '{print $3;}')
echo $stat_peak

